apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-project

resources:
  - secret.yaml
  - pvc.yaml
  - services.yaml
  - mysql-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - route.yaml

commonLabels:
  app: bookstore
